//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAuthorization.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Пароль { get; set; }
        public string КодовоеСлово { get; set; }
        public string ОтветНаСекрет { get; set; }
        public int КодСекрета { get; set; }
        public int КодПользователя { get; set; }
    
        public virtual СекретныйВопрос СекретныйВопрос { get; set; }
    }
}
